#!/bin/bash

# не вынести ли это в /etc/default/syncserver ?
ERL_PATH=usr/share/syncserver/ebin
CONFIG_FILE=etc/syncserver/syncserver.config
COOKIE_FILE=etc/syncserver/cookie
SNAME="syncserver@`uname -n`"
CONTROL_SNAME="syncserverctl"
DATABASE_DIR=var/syncserver/database
SYNCSERVER_USER=syncserver

WORK_DIR=/

print_help(){
	echo "Synchronization Server control script"
	echo "Usage:"
	echo " $0 start|stop|status|reload|"
	echo "    |force-reload|create-db|create-cookie  [--workdir DIR] [--no-su]"
}

if [ $# -eq 0 ] ; then
	print_help
	exit
fi

ARG1=$1

shift

while [ $# -gt 0 ]; do
	case $1 in 
		--no-su)
			#echo "not using \"su\""
			NO_SU=true
		;;
		--workdir)
			shift
			if [ -d "$1" ]; then
				WORK_DIR="$1"
				#echo "cd to directory \"$1\""
			else 
				echo "Wrong directory in option --workdir (\"$1\")"
			fi
		;;
		*)
			echo "Wrong argument: $1"
	esac
	shift
done

cd "$WORK_DIR"

START_SCRIPT="
	Result=rpc:call('$SNAME',util,start,[]),
	if	Result -> init:stop(0);
		true -> init:stop(1)
	end."

STOP_SCRIPT="
	rpc:call('$SNAME',util,stop,[]),
	init:stop(0)."

STATUS_SCRIPT="
	Result=rpc:call('$SNAME',util,status,[]),
	if	Result -> init:stop(0);
		true -> init:stop(1)
	end."

CREATE_DB_SCRIPT="
	R=rpc:call('$SNAME',util,create_db,[]),
	if	R==ok -> init:stop(0);
		true -> init_stop(1)
	end."

as_syncserver(){
	if [ -z "$NO_SU" ]; then
		su $SYNCSERVER_USER -- -c "$*"
	else
		bash -c "$*"
	fi
}

COOKIE=$(as_syncserver "cat $COOKIE_FILE 2>/dev/null" )

COOKIE_OPT="-setcookie $COOKIE"
test -z $COOKIE && COOKIE_OPT=

ERL_OPTIONS="-detached -pa $ERL_PATH -sname $SNAME -config $CONFIG_FILE $COOKIE_OPT"
ERL_OPTIONS_CONTROL="-noshell -sname $CONTROL_SNAME $COOKIE_OPT"
ERL_OPTIONS_CREATEDB="-noshell -pa $ERL_PATH -sname $CONTROL_SNAME -config $CONFIG_FILE $COOKIE_OPT"

#запуск рабочего узла
startnode(){
	as_syncserver "erl $ERL_OPTIONS"
}

# запуск контролирующего узла
# $* - выполняемый сценарий
ctl(){
	erl $ERL_OPTIONS_CONTROL -eval "$*"
}

#по сути stop_server делает то же..
stopnode(){
	ctl "rpc:call('$SNAME',init,stop,[]),init:stop()."
}

print_ok_fail(){
	if [ "$1" -eq 0 ];then
		echo " OK"
	else
		echo " FAIL"
	fi
	return $1
}


status(){
	echo -n "Checking SyncServer status.."
	ctl "$STATUS_SCRIPT"
	R=$?
	if [ "$R" -eq 0 ];then
		echo " OK"
	else
		echo " not running"
	fi
	return $R
}

stop_server(){
	echo -n "Stopping SyncServer.."	
	if status >/dev/null; then 
		ctl "$STOP_SCRIPT" >/dev/null
		print_ok_fail "$?"
	else 
		echo " not running."
	fi
}

start_server(){
	echo -n "Starting SyncServer.."	
	if status >/dev/null; then 
		echo " already started."
	else 
		{ startnode && ctl "$START_SCRIPT" ; }>/dev/null
		print_ok_fail "$?"
	fi
}

reload(){
	stop_server
	start_server
}

create_db(){
	echo -n "Creating database.."	
	if status>/dev/null; then
		echo " FAIL: Syncserver is running"
		return 1
	fi
	#TODO: надо проверять дополнительно, не запущен ли узел $SNAME,
	# или mnesia в каталоге mnesia dir..
	# часто в этом месте erl падает
	{ startnode && ctl "$CREATE_DB_SCRIPT" && stopnode ; } >/dev/null
	print_ok_fail "$?"
}
create_cookie(){
	{ cat /dev/urandom|head -c32|md5sum|head -c32 > $COOKIE_FILE
	} &&	chmod 440 $COOKIE_FILE && \
		chown $SYNCSERVER_USER:$SYNCSERVER_USER $COOKIE_FILE && \
		echo "Cookie file created."
}
case $ARG1 in
	status)
		status || true
	;;
	start) 
		start_server
	;;
	stop)
	    stop_server
	;;
	reload|force-reload)
		reload
	;;
	create-db)
	    create_db
	;;
	create-cookie-force)
	    create_cookie
	;;
	create-cookie)
		if [ -f $COOKIE_FILE ] ;then 
			echo -n "Cookie file already exists, "
			echo "try create-cookie-force to replace it"
			exit 1
		else
			create_cookie
		fi
	;;
	*)
		print_help
		exit 1
	;;
esac

